spring:
  application:
    name: rastibot-birthday-reminder-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL}/${DATASOURCE_DBNAME}
    username: rastibot-birthday-reminder-service
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: on
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

logging:
  level:
    root: INFO
    com.sbrati: INFO

google-cloud:
  project-id: ${BIRTHDAY_REMINDER_GOOGLE_CLOUD_PROJECT_ID}
  pub-sub:
    publish:
      topics:
        - key: check-birthday-reminder-exists-result
          name: ${BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_TOPICS_CHECK_BIRTHDAY_REMINDER_EXISTS_RESULT}
        - key: create-birthday-reminder-result
          name: ${BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_TOPICS_CREATE_BIRTHDAY_REMINDER_RESULT}
        - key: birthday-reminder-notification
          name: ${BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_TOPICS_BIRTHDAY_REMINDER_NOTIFICATION}
        - key: birthday-reminder-notification-action-result
          name: ${BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_TOPICS_BIRTHDAY_REMINDER_NOTIFICATION_ACTION_RESULT}
    subscribe:
      subscriptions:
        - key: check-birthday-reminder-exists
          name: ${BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_CHECK_BIRTHDAY_REMINDER_EXISTS}
        - key: create-birthday-reminder
          name: ${BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_CREATE_BIRTHDAY_REMINDER}
        - key: birthday-reminder-notification-action
          name: ${BIRTHDAY_REMINDER_SERVICE_GOOGLE_CLOUD_PUB_SUB_SUBSCRIPTIONS_BIRTHDAY_REMINDER_NOTIFICATION_ACTION}

birthday-reminder-service:
  batch-size: ${BIRTHDAY_REMINDER_SERVICE_BATCH_SIZE:100}
  schedule:
    enabled: true
    cron: ${BIRTHDAY_REMINDER_SERVICE_SCHEDULE_CRON:0 0 8 * * *}
